// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"shortener/shortener/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:shortUrl",
				Handler: ShowHandler(serverCtx),
			},
			{
				// 转换函数
				Method:  http.MethodPost,
				Path:    "/convert",
				Handler: ConvertHandler(serverCtx),
			},
			{
				// 查询短链累计访问次数
				// 注意：静态前缀 /stats 优先级高于通配符路由 /:shortUrl，不会冲突
				Method:  http.MethodGet,
				Path:    "/stats/:shortUrl",
				Handler: StatsHandler(serverCtx),
			},
		},
	)
}
